### 텐서플로 기초연산
rank 텐서플로의 차원
shape 텐서의 행과 열
type 텐서의 데이터 형식

##### 텐서를 만드는 방법
    - Numpy 등을 이용해 N차원 배열생성
    - N차원 배열을 텐서플로 텐서로 변환




In [1]:
import numpy as np

## Numpy lib 이용해서 배열 생성
tensor_1d = np.array([1.3,1,4.0,23.99])
print(tensor_1d)

[  1.3    1.     4.    23.99]


In [2]:
#배열접근
print(tensor_1d[0])

1.3


In [3]:
#rank 조회
tensor_1d.ndim

1

In [4]:
#튜플 조회
tensor_1d.shape

(4,)

In [5]:
# 데이터형 조회
tensor_1d.dtype

dtype('float64')

In [6]:

import tensorflow as tf

#텐서로 변환
tf_tensor = tf.convert_to_tensor(tensor_1d,dtype=tf.float64)

with tf.Session() as sess:
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[0]))
    print(sess.run(tf_tensor[1]))

[  1.3    1.     4.    23.99]
1.3
1.0


### 2차원 텐서

In [20]:
import numpy as np

#2차원 배열 생성 
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11)])
tensor_2d_2 = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
print(tensor_2d)
print(tensor_2d_2)

#Element 확인
print(tensor_2d[1,1])
print(tensor_2d[2,3])
print(tensor_2d[0:3,0:3]) # 0~3,0~3 

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5
11
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [23]:
#텐서 다루기
import numpy as np

m1 = np.array([[2,2,2],[2,2,2],[2,2,2]],dtype='int32')
m2 = np.array([[1,1,1],[1,1,1],[1,1,1]],dtype='int32')

print("m1 =")
print(m1)
print("m2 =")
print(m2)

m1 =
[[2 2 2]
 [2 2 2]
 [2 2 2]]
m2 =
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
tfm1 = tf.constant(m1)
tfm2 = tf.constant(m2)

# 곱
mProduct = tf.matmul(tfm1,tfm2)
# 덧셈
mSum = tf.add(tfm1,tfm2)

#행렬식
m3 = np.array([[2,7,2],[1,4,2],[9,0,2]],dtype='float32')

print("m3 =")
print(m3)

tfm3 = tf.matrix_determinant(m3)

with tf.Session() as sess:
    result1 = sess.run(mProduct)
    result2 = sess.run(mSum)
    result3 = sess.run(tfm3)

#행렬 곱 
print("m1 * m2= ")
print(result1)

#행렬 덧셈
print("m1 + m2 =")
print(result2)

## 뭔지모름 찾아볼것
print("m3 determinant result =")
print(result3)

m3 =
[[ 2.  7.  2.]
 [ 1.  4.  2.]
 [ 9.  0.  2.]]
m1 * m2= 
[[6 6 6]
 [6 6 6]
 [6 6 6]]
m1 + m2 =
[[3 3 3]
 [3 3 3]
 [3 3 3]]
m3 determinant result =
56.0


### 3차원 텐서

# import numpy as np
tensor_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor_3d)

tensor_3d.shape

In [34]:
#tensor_3d[plane,row,col]
print(tensor_3d[0,0,1])
print(tensor_3d[0,1,1])
print(tensor_3d[1,1,1])

2
4
8


### Tensorflow로 이미지를 불러오고 슬라이스해서 이미지의 일부분을 추출 해보자

In [ ]:
import matplotlib.image as mp_image
filename = "packt.jped"
## ... 다음 사람이 하자.